<?php

namespace GSB\ObjComBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PharmacieProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PharmacieProduitRepository extends EntityRepository
{
}
