<?php

namespace GSB\ObjComBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * PharmacieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PharmacieRepository extends EntityRepository
{
    public function toutesLesPharmacies(){
        $qb=$this->createQueryBuilder('p');
        $qry=$qb->getQuery();
        $res=$qry->getResult();
        return $res;
    }
    public function unePharmacie($idPharm)
    {
        $qb= $this->createQueryBuilder('p');
        $qb->where('p.id = :parid')->setParameter('parid',$idPharm);
        return $qb->getQuery()->getResult();
    }
    public function rechercherVilleEtAnneeCreation($ville,$date)
    {
        $qb= $this->createQueryBuilder('p');
        $qb->where('p.ville = :uneUVille')->setParameter('uneVille',$ville)->andWhere('p.datecreation >:uneDate')->orderBy('p.datecreation','DESC');
        return $qb->getQuery()->getResult();
    }
    
    public function dernieresPharmaciesCrees($limit)
	{
		$qb=$this->createQueryBuilder('p');
		$qb->select('p');
                $qb->where('p.client=true');
		$qb->orderBy('p.dateajout','ASC');
		$qb->setMaxResults($limit);
		return $qb->getQuery()->getResult();
	}

    
}