<?php

namespace GSB\ObjComBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends EntityRepository
{

    public function derniersProduitsCrees($limit)
    {
        $qb=$this->createQueryBuilder('p');
        $qb->select('p');
        $qb->where('p.isSold=true');
        $qb->setMaxResults($limit);
        return $qb->getQuery()->getResult();
    }
}
